[package]
name = "practice_6_5_20"
version = "0.1.0"
authors = ["muhammad"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
